name: build-and-test

on:
  workflow_dispatch:
  push:
    branches: ["*"]
  pull_request_target:
    branches: ["*"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Run npm install
        run: |
          npm run preinstall
          npm set-script preinstall ""
          npm ci
      - run: npm run compile
      - run: npm test
